# Database Configuration
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gym_database
    username: root
    password: qays2002
    driver-class-name: com.mysql.cj.jdbc.Driver

  # Hibernate Configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
